# Generated by Django 4.2.3 on 2023-07-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="comment",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
