# Generated by Django 4.2.3 on 2023-07-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0003_alter_purchase_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="comment",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="supplier",
            field=models.URLField(default=""),
        ),
    ]
