# Generated by Django 4.2.3 on 2023-08-27 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0005_purchase_create_date_purchase_last_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="funding",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funding",
            name="last_update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
