# Generated by Django 4.2.3 on 2023-08-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0006_funding_create_date_funding_last_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="funding",
            name="comment",
            field=models.CharField(default="", max_length=64),
        ),
    ]
